# BlockZone Lab - API Worker Configuration
name = "blockzonelab-api"
main = "minimal-worker.js"
compatibility_date = "2025-01-15"

# Production Routes
routes = ["https://api.blockzonelab.com/*"]

# Core Data Storage - Optimized for BlockZone Lab Architecture
[[kv_namespaces]]
binding = "PLAYERS"
id = "afdca5fda8b343b99541432574cfa5c3"

[[kv_namespaces]]
binding = "SCORES"
id = "8e4d3de3c359495186eabf9032d08d8f"

[[kv_namespaces]]
binding = "LEADERBOARDS"
id = "11432812fab64eb785a75cbdd0e40029"

# Game-Specific Data
[[kv_namespaces]]
binding = "GAMING"
id = "8e4d3de3c359495186eabf9032d08d8f"

# Financial and Payment Data
[[kv_namespaces]]
binding = "FINANCIAL"
id = "11432812fab64eb785a75cbdd0e40029"

# Social and Community Features
[[kv_namespaces]]
binding = "SOCIAL"
id = "9472d4328eda428090494844a4cdba9b"

# Analytics and User Behavior
[[kv_namespaces]]
binding = "ANALYTICS"
id = "66d8e0a1ead24a9c916bd22551cf1515"

# Challenge System
[[kv_namespaces]]
binding = "CHALLENGES"
id = "d4f40a571cdc49a98d5dd1d9f3a983ea"

# Session Management
[[kv_namespaces]]
binding = "SESSIONS"
id = "707b56866f89485f9e074d81614b66b3"

# Legacy Compatibility (for existing data)
[[kv_namespaces]]
binding = "REWARDS"
id = "66d8e0a1ead24a9c916bd22551cf1515"

[[kv_namespaces]]
binding = "TOURNAMENTS"
id = "d4f40a571cdc49a98d5dd1d9f3a983ea"

[[kv_namespaces]]
binding = "WALLETS"
id = "707b56866f89485f9e074d81614b66b3"

# Environment Variables
[vars]
# Platform Configuration
PLATFORM_NAME = "BlockZone Lab"
PLATFORM_VERSION = "3.0.0"
DEFAULT_TIMEZONE = "America/New_York"
DEFAULT_LANGUAGE = "en"
DEFAULT_COUNTRY = "US"

# Development Configuration
NODE_ENV = "production"
ENABLE_DEBUG_LOGS = "true"
ENABLE_PERFORMANCE_MONITORING = "true"

# Security Configuration
SEED_SALT = "blockzone_secure_seed_salt_2024_v3"
JWT_SECRET = "blockzone_jwt_secret_2024_v3"

# Game Configuration
MAX_SCORES_PER_DAY = "100"
MAX_PLAYERS_PER_LEADERBOARD = "1000"
FREE_GAMES_PER_DAY = "1"
UNLIMITED_PASS_DURATION_HOURS = "24"

# API Rate Limiting
RATE_LIMIT_REQUESTS_PER_MINUTE = "100"
RATE_LIMIT_BURST_SIZE = "20"

# Performance Optimization
minify = true
compatibility_flags = ["nodejs_compat"]

# Worker Settings
WORKER_TIMEOUT_MS = "30000"
MAX_CONCURRENT_REQUESTS = "100"
