name = "blockzonelab-api"
main = "minimal-worker.js"
compatibility_date = "2025-07-15"

# Route for custom domain - ENABLED
routes = ["https://api.blockzonelab.com/*"]

# Core player data
[[kv_namespaces]]
binding = "PLAYERS"
id = "afdca5fda8b343b99541432574cfa5c3"

# Gaming statistics and achievements
[[kv_namespaces]]
binding = "GAMING"
id = "8e4d3de3c359495186eabf9032d08d8f"

# Financial data and payments
[[kv_namespaces]]
binding = "FINANCIAL"
id = "11432812fab64eb785a75cbdd0e40029"

# Social connections and community
[[kv_namespaces]]
binding = "SOCIAL"
id = "9472d4328eda428090494844a4cdba9b"

# Analytics and behavioral tracking
[[kv_namespaces]]
binding = "ANALYTICS"
id = "66d8e0a1ead24a9c916bd22551cf1515"

# Challenge system
[[kv_namespaces]]
binding = "CHALLENGES"
id = "d4f40a571cdc49a98d5dd1d9f3a983ea"

# Sessions and authentication
[[kv_namespaces]]
binding = "SESSIONS"
id = "707b56866f89485f9e074d81614b66b3"

# Legacy namespaces for backward compatibility
[[kv_namespaces]]
binding = "SCORES"
id = "8e4d3de3c359495186eabf9032d08d8f"

[[kv_namespaces]]
binding = "LEADERBOARDS"
id = "11432812fab64eb785a75cbdd0e40029"

[[kv_namespaces]]
binding = "REWARDS"
id = "66d8e0a1ead24a9c916bd22551cf1515"

[[kv_namespaces]]
binding = "TOURNAMENTS"
id = "d4f40a571cdc49a98d5dd1d9f3a983ea"

[[kv_namespaces]]
binding = "WALLETS"
id = "707b56866f89485f9e074d81614b66b3"

[vars]
# Platform configuration
PLATFORM_NAME = "BlockZone Lab"
PLATFORM_VERSION = "3.0.0"
DEFAULT_TIMEZONE = "America/New_York"
DEFAULT_LANGUAGE = "en"
DEFAULT_COUNTRY = "US"

# Security configuration
SEED_SALT = "blockzone_secure_seed_salt_2024_v3"
