# BlockZone Lab Fresh - Clean API Worker Configuration
# Extracted from your proven backend architecture

name = "blockzonelab-fresh-api"
main = "worker.js"
compatibility_date = "2025-01-15"

# Production Routes
routes = ["https://api-fresh.blockzonelab.com/*"]

# Your proven KV namespace structure - Clean and organized
[[kv_namespaces]]
binding = "PLAYERS"
id = "fresh-players-namespace"
preview_id = "fresh-players-preview"

[[kv_namespaces]]
binding = "SCORES"
id = "fresh-scores-namespace"
preview_id = "fresh-scores-preview"

[[kv_namespaces]]
binding = "LEADERBOARDS"
id = "fresh-leaderboards-namespace"
preview_id = "fresh-leaderboards-preview"

[[kv_namespaces]]
binding = "SESSIONS"
id = "fresh-sessions-namespace"
preview_id = "fresh-sessions-preview"

# Environment variables for production
[env.production]
name = "blockzonelab-fresh-api-prod"

[env.staging]
name = "blockzonelab-fresh-api-staging"
